(()=>{'use strict';
const KEY='gugungSudoku.v1';
const HOME_KEY='gugungHome.v1';
const MAX_STAGE=100;
const LEVELS={easy:{ko:'고요',p:'530070000600195000098000060800060003400803001700020006060000280000419005000080079'},medium:{ko:'사유',p:'000260701680070090190004500820100040004602900050003028009300074040050036703018000'},hard:{ko:'심연',p:'005300000800000020070010500400005300010070006003200080060500009004000030000009700'}};
const OUTFITS=[{id:'casual',type:'daily',name:'데일리 후드',price:0,file:'assets/modern-woman-v2.png'},{id:'dress',type:'daily',name:'코랄 원피스',price:220,file:'assets/modern-woman-dress.png'},{id:'school',type:'daily',name:'라벤더 교복',price:180,file:'assets/luna-school.png'},{id:'weekend',type:'daily',name:'포근한 주말룩',price:260,file:'assets/luna-weekend.png'},{id:'magic',type:'magic',name:'기본 변신폼',price:0,file:'assets/modern-woman-magic-lavender.png'},{id:'moonlight',type:'magic',name:'문라이트 드레스',price:700,file:'assets/modern-woman-moonlight-v2.png'},{id:'rose',type:'magic',name:'로즈 코멧 폼',price:900,file:'assets/luna-magic-rose.png'},{id:'midnight',type:'magic',name:'미드나이트 프리즘',price:1200,file:'assets/luna-magic-midnight.png'}];
const WANDS=[{id:'bare',name:'마법봉 없음',icon:'',price:0,atk:0,pos:[0,0]},{id:'branch',name:'낡은 나뭇가지',icon:'🌿',price:0,atk:3,pos:[0,0]},{id:'star',name:'별빛 마법봉',icon:'🪄',price:250,atk:12,pos:[1,0]},{id:'moon',name:'초승달 스태프',icon:'🌙',price:500,atk:24,pos:[0,1]},{id:'crystal',name:'크리스털 로드',icon:'💎',price:850,atk:40,pos:[1,1]}];
const PETS=[{id:'none',name:'함께하지 않기',file:'',price:0,ability:''},{id:'weasel',name:'별족제비 루미',file:'assets/pet-lumi.png',price:0,ability:'별빛 돌진 · 12 피해'},{id:'rabbit',name:'별토끼 모모',file:'assets/pet-rabbit.png',price:320,ability:'달빛 응원 · 체력 35 회복'},{id:'fox',name:'별여우 코코',file:'assets/pet-star-fox-v2.png',price:430,ability:'꼬리 보호막 · 다음 피해 15 감소'},{id:'bat',name:'달박쥐 네네',file:'assets/pet-moon-bat.png',price:520,ability:'그림자 교란 · 적 공격력 4 감소'},{id:'owl',name:'구름부엉이 포포',file:'assets/pet-cloud-owl.png',price:610,ability:'별구름 · 8 피해와 체력 18 회복'}];
const TRANSFORMS=[{id:'none',name:'변신 아이템 없음',price:0,pos:[0,0],outfit:'magic'},{id:'starPrism',name:'코멧 스타 키',price:300,pos:[0,0],outfit:'magic'},{id:'moonCompact',name:'미드나이트 아워',price:480,pos:[1,0],outfit:'moonlight'},{id:'flowerCompact',name:'문셸 콤팩트',price:650,pos:[0,1],outfit:'rose'},{id:'heartCompact',name:'아스트라 북 콤팩트',price:820,pos:[1,1],outfit:'midnight'}];
const BOSSES=[{stage:20,name:'가시정원 슬라임',hp:50,atk:4,reward:120,pos:[0,0]},{stage:40,name:'초승달 까마귀',hp:85,atk:6,reward:220,pos:[1,0]},{stage:60,name:'태엽 갑옷게',hp:125,atk:8,reward:340,pos:[2,0]},{stage:80,name:'수정갈기 늑대',hp:170,atk:10,reward:480,pos:[0,1]},{stage:100,name:'별그림자 용',hp:230,atk:12,reward:700,pos:[1,1]}];
let state={screen:'title',level:'easy',puzzle:'',solution:'',values:Array(81).fill(0),notes:Array.from({length:81},()=>[]),selected:-1,mistakes:0,hints:3,elapsed:0,paused:false,history:[],seed:0};let clock=null;
let home=loadHome(),closetOpen=false,researchOpen=false,previewOutfit=null,previewKind='outfit',previewEquipment=null;
let battleState=null,developerMode=false;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function solve(str){const a=str.split('').map(Number);function go(){let idx=-1,best=null;for(let i=0;i<81;i++)if(!a[i]){const used=new Set();let r=Math.floor(i/9),c=i%9;for(let k=0;k<9;k++){used.add(a[r*9+k]);used.add(a[k*9+c]);}let br=Math.floor(r/3)*3,bc=Math.floor(c/3)*3;for(let y=0;y<3;y++)for(let x=0;x<3;x++)used.add(a[(br+y)*9+bc+x]);let opts=[];for(let n=1;n<=9;n++)if(!used.has(n))opts.push(n);if(!opts.length)return false;if(!best||opts.length<best.length){best=opts;idx=i;if(opts.length===1)break;}}if(idx<0)return true;for(const n of best){a[idx]=n;if(go())return true;a[idx]=0;}return false;}return go()?a.join(''):'';}
function mulberry32(a){return()=>{let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function transformed(base,seed){let rng=mulberry32(seed),shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a},map=shuffle([1,2,3,4,5,6,7,8,9]),bands=shuffle([0,1,2]),stacks=shuffle([0,1,2]),rows=bands.flatMap(b=>shuffle([0,1,2]).map(x=>b*3+x)),cols=stacks.flatMap(b=>shuffle([0,1,2]).map(x=>b*3+x)),out='';for(const r of rows)for(const c of cols){let d=+base[r*9+c];out+=d?map[d-1]:0}return out;}
function defaultHome(){return{coins:0,totalScore:0,unlockedStage:1,stageStars:{},bossCleared:[],ownedOutfits:['casual','magic'],outfit:'casual',lastDaily:'casual',lastMagic:'magic',ownedWands:['bare','branch'],wand:'branch',ownedTransforms:['none'],transform:'none',ownedPets:['none','weasel'],pet:'weasel',hpPotionStock:0,mpPotionStock:0,starlightLevel:0,rewarded:[]}}
function loadHome(){try{let h=JSON.parse(localStorage.getItem(HOME_KEY)||'null'),d=defaultHome(),m=Object.assign(d,h||{}),valid=(list,catalog,required=[])=>[...new Set([...required,...(Array.isArray(list)?list:[])])].filter(id=>catalog.some(x=>x.id===id));m.rewarded=Array.isArray(m.rewarded)?m.rewarded.map(String).slice(-MAX_STAGE):[];m.totalScore=Number.isFinite(+m.totalScore)?Math.max(0,+m.totalScore):0;m.coins=Number.isFinite(+m.coins)?Math.max(0,+m.coins):0;m.unlockedStage=Math.min(MAX_STAGE,Math.max(1,Number.isInteger(+m.unlockedStage)?+m.unlockedStage:1));m.stageStars=m.stageStars&&typeof m.stageStars==='object'?Object.fromEntries(Object.entries(m.stageStars).filter(([k,v])=>+k>=1&&+k<=MAX_STAGE&&[1,2,3].includes(+v)).map(([k,v])=>[k,+v])):{};m.bossCleared=Array.isArray(m.bossCleared)?[...new Set(m.bossCleared.map(Number).filter(n=>BOSSES.some(b=>b.stage===n)))]:[];m.ownedOutfits=valid(m.ownedOutfits,OUTFITS,['casual','magic']);m.outfit=m.ownedOutfits.includes(m.outfit)?m.outfit:'casual';m.lastDaily=m.ownedOutfits.includes(m.lastDaily)&&!isMagicOutfit(m.lastDaily)?m.lastDaily:'casual';m.lastMagic=m.ownedOutfits.includes(m.lastMagic)&&isMagicOutfit(m.lastMagic)?m.lastMagic:'magic';let legacyWands=Array.isArray(m.ownedWands)?m.ownedWands.map(id=>id==='none'?'branch':id):[];m.ownedWands=valid(legacyWands,WANDS,['bare','branch']);m.wand=m.wand==='none'?'branch':m.wand;m.wand=m.ownedWands.includes(m.wand)?m.wand:'branch';m.ownedTransforms=valid(m.ownedTransforms,TRANSFORMS,['none']);m.transform=m.ownedTransforms.includes(m.transform)?m.transform:'none';m.ownedPets=valid(m.ownedPets,PETS,['none','weasel']);m.pet=m.ownedPets.includes(m.pet)?m.pet:'weasel';m.hpPotionStock=Math.max(0,Math.floor(+(m.hpPotionStock??m.potionStock)||0));m.mpPotionStock=Math.max(0,Math.floor(+m.mpPotionStock||0));delete m.potionStock;m.starlightLevel=Math.min(3,Math.max(0,Math.floor(+m.starlightLevel||0)));delete m.wandLevels;delete m.boostStock;return m}catch(e){return defaultHome()}}
function saveHome(){if(developerMode)return;try{localStorage.setItem(HOME_KEY,JSON.stringify(home))}catch(e){}}
function grantDeveloperInventory(){if(!developerMode)return;home.coins=10000;home.ownedOutfits=OUTFITS.map(x=>x.id);home.ownedWands=WANDS.map(x=>x.id);home.ownedTransforms=TRANSFORMS.map(x=>x.id);home.ownedPets=PETS.map(x=>x.id);home.hpPotionStock=99;home.mpPotionStock=99;home.starlightLevel=3}
function returnShards(h=home){return Math.min(5,Math.floor((h.rewarded?.length||0)/3))}
function wandHTML(item,cls=''){let[x,y]=item.pos||[0,0];return `<span class="${cls} wand-sprite" style="--wx:${x*100}%;--wy:${y*100}%" role="img" aria-label="${item.name}"></span>`}
function transformHTML(item,cls=''){let[x,y]=item.pos||[0,0];return `<span class="${cls} transform-sprite" style="--tx:${x*100}%;--ty:${y*100}%" role="img" aria-label="${item.name}"></span>`}
function setHomeMessage(t){let x=$('#homeMessage');if(x)x.textContent=t}
function renderGrowth(){let shards=returnShards();$("#homeShards").textContent=shards+" / 5 조각"}
function openHome(){closetOpen=false;researchOpen=true;show('home');stopClock();renderHome()}
function preserveInventoryScroll(draw){
 const ids=['home','gearCloset','researchLab'];
 const positions=ids.map(id=>{const el=document.getElementById(id);return el?{el,x:el.scrollLeft,y:el.scrollTop}:null}).filter(Boolean);
 try{return draw()}finally{for(const p of positions){p.el.scrollLeft=p.x;p.el.scrollTop=p.y}}
}
function renderHome(){return preserveInventoryScroll(renderHomeContent)}
function renderCloset(){return preserveInventoryScroll(()=>{renderClosetContent();updateEmptyClosetRows()})}
function updateEmptyClosetRows(){['ownedOutfits','ownedWands','ownedTransforms','ownedPets'].forEach(id=>{let row=document.getElementById(id);if(!row)return;let empty=row.childElementCount===0;row.hidden=empty;let label=row.previousElementSibling;if(label?.classList.contains('closet-label'))label.hidden=empty})}
function canEditPuzzle(){return state.screen==='game'&&!state.paused&&!state.complete}

function renderHomeContent(){
 home=loadHome();grantDeveloperInventory();if(isMagicOutfit(home.outfit))home.lastMagic=home.outfit;else home.lastDaily=home.outfit;$('#coins').textContent=home.coins.toLocaleString('ko-KR');
 $('#openCloset').classList.toggle('primary',closetOpen);$('#openCloset').textContent=closetOpen?'옷장 닫기':'옷장';$('#openResearch').classList.toggle('primary',researchOpen);$('#researchLab').hidden=!researchOpen;
 let outfit=OUTFITS.find(x=>x.id===home.outfit)||OUTFITS[0],pet=PETS.find(x=>x.id===home.pet)||PETS[0],wand=WANDS.find(x=>x.id===home.wand)||WANDS[0],transform=TRANSFORMS.find(x=>x.id===home.transform)||TRANSFORMS[0];$('#cat').src=outfit.file;$('#cat').className='cat';$('#pet').hidden=pet.id==='none';if(pet.id!=='none'){$('#petImage').src=pet.file;$('#petName').textContent=pet.name.split(' ').pop()}$('#wandDisplay').innerHTML=wand.id==='bare'?'':wandHTML(wand);$('#transformDisplay').hidden=transform.id==='none';$('#transformDisplay').innerHTML=transform.id==='none'?'':transformHTML(transform);$('#quickTransform').textContent=isMagicOutfit(home.outfit)?'변신 해제':'✦ 변신하기';renderGrowth();renderResearch();renderCloset();saveHome();renderShop()
}
function renderResearch(){let panel=$('#researchLab');if(!panel)return;let level=home.starlightLevel,cost=[100,180,300][level],maxed=level>=3;$('#starlightLevel').textContent=`별빛술 Lv.${level}`;$('#starlightCost').textContent=maxed?'최대 연구 완료':`${cost} P · 별빛 공격 +3`;$('#upgradeStarlight').disabled=maxed}
function upgradeStarlight(){let level=home.starlightLevel;if(level>=3)return;let cost=[100,180,300][level];if(home.coins<cost){toast(`포인트가 ${cost-home.coins}점 부족합니다`);return}home.coins-=cost;home.starlightLevel++;saveHome();renderHome();toast(`별빛술 Lv.${home.starlightLevel} 연구 완료`)}
function renderPotionShop(){let petSection=$('#petCatalog')?.closest('.shop-section');if(!petSection)return;let section=$('#potionShopSection');if(!section){section=document.createElement('div');section.id='potionShopSection';section.className='shop-section';section.innerHTML='<h3>포션</h3><div class="mini-catalog"><button id="buyHpPotion" class="shop-chip potion-product"><img src="assets/potion-hp.png" alt="HP 포션"><strong>HP 포션</strong><small>80 P · 보유 <b id="shopHpPotionStock">0</b></small></button><button id="buyMpPotion" class="shop-chip potion-product"><img src="assets/potion-mp.png" alt="MP 포션"><strong>MP 포션</strong><small>80 P · 보유 <b id="shopMpPotionStock">0</b></small></button></div>';petSection.after(section);$('#buyHpPotion').onclick=()=>buyPotion('hp');$('#buyMpPotion').onclick=()=>buyPotion('mp')}$('#shopHpPotionStock').textContent=home.hpPotionStock;$('#shopMpPotionStock').textContent=home.mpPotionStock}
function buyPotion(type){if(home.coins<80){toast(`포인트가 ${80-home.coins}점 부족합니다`);return}home.coins-=80;home[type==='hp'?'hpPotionStock':'mpPotionStock']++;saveHome();renderShop();toast(`${type.toUpperCase()} 포션 구매 완료`)}
function novaSay(text){let box=$('#novaTalk');if(box)box.innerHTML=`<strong>노바 아저씨</strong>${text}`}
function openShopScreen(){previewOutfit=home.outfit;previewKind='none';previewEquipment=null;show('shop');renderShop();novaSay(['어서 와. 오늘은 뭘 살 생각이니?','스도쿠 포인트는 현명하게 쓰는 게 좋아.','입어보는 건 무료란다. 천천히 골라봐.'][Math.floor(Math.random()*3)])}
function removeShopOutfitSections(){let daily=$('#dailyWardrobe')?.closest('.drawer-head'),magic=$('#magicWardrobe')?.closest('.shop-section');daily?.remove();magic?.remove()}
function renderShop(){home=loadHome();if(developerMode)home.coins=10000;removeShopOutfitSections();if(!OUTFITS.some(o=>o.id===previewOutfit))previewOutfit=home.outfit;let wallet=$('#shopCoins');if(wallet)wallet.textContent=home.coins.toLocaleString('ko-KR');if($('#fittingImage'))renderFitting();if(previewKind==='wand'){let w=WANDS.find(x=>x.id===previewEquipment);if(w)$('#fittingName').innerHTML=`${w.name}<small class="attack-stat">공격력 ${w.atk}</small>`}if($('#wandCatalog'))renderWands();if($('#transformCatalog'))renderTransforms();if($('#petCatalog'))renderPets();renderPotionShop()}
function isMagicOutfit(id){return OUTFITS.find(o=>o.id===id)?.type==='magic'}
function renderWardrobe(){$('#quickTransform').textContent=isMagicOutfit(home.outfit)?'변신 해제':'✦ 변신하기';renderOutfitGroup('#dailyWardrobe','daily','모든 일상 의상을 보유 중이에요.');renderOutfitGroup('#magicWardrobe','magic','모든 마법소녀 의상을 보유 중이에요.')}
function renderOutfitGroup(selector,type,emptyText){let box=$(selector),items=OUTFITS.filter(o=>o.type===type&&!home.ownedOutfits.includes(o.id));box.innerHTML='';if(!items.length){box.innerHTML=`<small class="sold-out">${emptyText}</small>`;return}items.forEach(o=>{let b=document.createElement('button');b.className=`outfit-btn locked ${previewKind==='outfit'&&previewOutfit===o.id?'active':''}`;b.innerHTML=`${type==='magic'?'✦ ':''}${o.name}<small>${o.price} P</small>`;b.onclick=()=>{previewKind='outfit';previewOutfit=o.id;previewEquipment=null;renderShop();novaSay(`${o.name}? 루나에게 잘 어울리는지 먼저 보렴.`)};box.appendChild(b)})}
function renderFitting(){let img=$('#fittingImage'),wand=$('#fittingWand'),transform=$('#fittingTransform'),pet=$('#fittingPet'),action=$('#fittingAction'),name=$('#fittingName'),status=$('#fittingStatus'),previewedOutfit=OUTFITS.find(x=>x.id===previewOutfit)||OUTFITS.find(x=>x.id===home.outfit)||OUTFITS[0];wand.hidden=true;transform.hidden=true;pet.hidden=true;action.hidden=false;img.src=previewedOutfit.file;name.parentElement.hidden=previewKind==='none';if(previewKind==='none'){name.textContent='';status.textContent='';action.hidden=true;action.onclick=null;return}if(previewKind==='wand'){let o=WANDS.find(x=>x.id===previewEquipment)||WANDS[0],owned=home.ownedWands.includes(o.id);wand.innerHTML=wandHTML(o);wand.hidden=false;name.textContent=o.name;status.textContent=owned?'보유 중':`루나 장착 미리보기 · 구매 ${o.price} P`;action.hidden=owned;action.textContent=`${o.price} P로 구매하기`;action.disabled=false;action.classList.add('buy');action.onclick=()=>buyEquip(o,'wand','ownedWands');return}if(previewKind==='transform'){let o=TRANSFORMS.find(x=>x.id===previewEquipment)||TRANSFORMS[0],owned=home.ownedTransforms.includes(o.id);transform.innerHTML=transformHTML(o);transform.hidden=false;name.textContent=o.name;status.textContent=owned?'보유 중':`루나 변신 아이템 미리보기 · 구매 ${o.price} P`;action.hidden=owned;action.textContent=`${o.price} P로 구매하기`;action.disabled=false;action.classList.add('buy');action.onclick=()=>buyEquip(o,'transform','ownedTransforms');return}if(previewKind==='pet'){let o=PETS.find(x=>x.id===previewEquipment)||PETS[1],owned=home.ownedPets.includes(o.id);pet.src=o.file;pet.alt=`미리 보는 ${o.name}`;pet.hidden=false;name.textContent=o.name;status.textContent=owned?'보유 중':`루나와 함께 보기 · 구매 ${o.price} P`;action.hidden=owned;action.textContent=`${o.price} P로 데려오기`;action.disabled=false;action.classList.add('buy');action.onclick=()=>buyEquip(o,'pet','ownedPets');return}let o=previewedOutfit,owned=home.ownedOutfits.includes(o.id);name.textContent=o.name;status.textContent=owned?'보유 중':`루나 착용 미리보기 · 구매 ${o.price} P`;action.hidden=owned;action.textContent=`${o.price} P로 구매하기`;action.disabled=false;action.classList.add('buy');action.onclick=()=>confirmPreviewOutfit(o)}
function confirmPreviewOutfit(o){if(home.ownedOutfits.includes(o.id))return;if(home.coins<o.price){toast(`포인트가 ${o.price-home.coins}점 부족합니다`);novaSay('입어보는 건 무료지만 구매할 포인트는 조금 부족하구나.');return}home.coins-=o.price;home.ownedOutfits.push(o.id);let next=OUTFITS.find(x=>!home.ownedOutfits.includes(x.id));previewOutfit=next?.id||home.outfit;previewKind='outfit';previewEquipment=null;saveHome();renderShop();toast(`${o.name} 구매 완료 · 옷장에 보관했어요`);novaSay('좋은 선택이야. 연구실 옷장에서 갈아입으렴.')}
function renderWands(){let current=WANDS.find(o=>o.id===home.wand)||WANDS[0],room=$('#wandDisplay');if(room)room.innerHTML=current.id==='bare'?'':wandHTML(current);let box=$('#wandCatalog'),items=WANDS.filter(o=>o.id!=='bare'&&!home.ownedWands.includes(o.id));box.innerHTML='';if(!items.length){box.innerHTML='<small class="sold-out">모든 마법봉을 보유 중이에요.</small>';return}items.forEach(o=>{let b=document.createElement('button');b.className=`shop-chip locked ${previewKind==='wand'&&previewEquipment===o.id?'active':''}`;b.innerHTML=`<strong>${wandHTML(o,'shop-wand')} ${o.name}<em class="attack-stat">공격력 ${o.atk}</em></strong><small>${o.price} P</small>`;b.onclick=()=>{previewKind='wand';previewEquipment=o.id;renderShop();novaSay(`${o.name}을 든 루나의 모습을 먼저 확인해 보렴.`)};box.appendChild(b)})}
function renderTransforms(){let box=$('#transformCatalog'),items=TRANSFORMS.filter(o=>o.id!=='none'&&!home.ownedTransforms.includes(o.id));box.innerHTML='';if(!items.length){box.innerHTML='<small class="sold-out">모든 변신 아이템을 보유 중이에요.</small>';return}items.forEach(o=>{let b=document.createElement('button');b.className=`shop-chip locked ${previewKind==='transform'&&previewEquipment===o.id?'active':''}`;b.innerHTML=`<strong>${transformHTML(o,'shop-transform')} ${o.name}</strong><small>${o.price} P</small>`;b.onclick=()=>{previewKind='transform';previewEquipment=o.id;previewOutfit=o.outfit;renderShop();novaSay(`${o.name}의 변신폼을 확인해 보렴.`)};box.appendChild(b)})}
function renderPets(){let box=$('#petCatalog'),items=PETS.filter(o=>o.id!=='none'&&!home.ownedPets.includes(o.id));box.innerHTML='';if(!items.length){box.innerHTML='<small class="sold-out">모든 펫과 함께하고 있어요.</small>';return}items.forEach(o=>{let b=document.createElement('button');b.className=`shop-chip locked ${previewKind==='pet'&&previewEquipment===o.id?'active':''}`;b.innerHTML=`<img class="shop-pet-image" src="${o.file}" alt="${o.name}"><strong>${o.name}</strong><em class="pet-ability">${o.ability}</em><small>${o.price} P</small>`;b.onclick=()=>{previewKind='pet';previewEquipment=o.id;renderShop();novaSay(`${o.name}와 루나가 잘 어울리는지 먼저 보렴.`)};box.appendChild(b)})}
function buyEquip(o,field,list){if(home[list].includes(o.id))return;if(home.coins<o.price){toast(`포인트가 ${o.price-home.coins}점 부족합니다`);novaSay('포인트가 조금 부족하네. 퍼즐 의뢰를 하나 더 해결하고 와.');return}home.coins-=o.price;home[list].push(o.id);if(field==='transform'&&o.outfit&&!home.ownedOutfits.includes(o.outfit))home.ownedOutfits.push(o.outfit);let catalog=field==='wand'?WANDS:field==='transform'?TRANSFORMS:PETS,next=catalog.find(x=>x.id!=='bare'&&x.id!=='none'&&!home[list].includes(x.id));if(next){previewEquipment=next.id;if(field==='transform')previewOutfit=next.outfit}else{previewKind='none';previewEquipment=null;previewOutfit=home.outfit}saveHome();renderShop();toast(`${o.name} 구매 완료 · 옷장에 보관했어요`);novaSay(`${o.name}, 좋은 선택이야. 연구실에서 사용하렴.`)}
function changeOutfit(id){let o=OUTFITS.find(x=>x.id===id);if(!home.ownedOutfits.includes(id)){if(home.coins<o.price){toast(`포인트가 ${o.price-home.coins}점 부족합니다`);novaSay('그 옷은 아직 조금 비싸지? 실력을 보여주고 다시 오렴.');return}home.coins-=o.price;home.ownedOutfits.push(id);toast(`${o.name} 구매 완료`);novaSay('아주 잘 어울리겠구나. 탈의실은 바로 안쪽이야.')}home.outfit=id;saveHome();renderHome();if(isMagicOutfit(id)){$('#homeMessage').textContent=`${o.name}으로 변신!`;$('#room').classList.add('transforming');setTimeout(()=>$('#room').classList.remove('transforming'),800)}else $('#homeMessage').textContent=`${o.name}으로 갈아입었어요.`}
function toggleTransform(){changeOutfit(isMagicOutfit(home.outfit)?home.lastDaily:home.lastMagic)}
function renderClosetContent(){let panel=$('#gearCloset');panel.hidden=!closetOpen;if(!closetOpen)return;let outfits=$('#ownedOutfits'),wands=$('#ownedWands'),transforms=$('#ownedTransforms'),pets=$('#ownedPets');outfits.innerHTML='';home.ownedOutfits.map(id=>OUTFITS.find(o=>o.id===id)).filter(Boolean).forEach(o=>{let b=document.createElement('button');b.className=`closet-card ${home.outfit===o.id?'active':''}`;b.innerHTML=`<img src="${o.file}" alt="">${o.name}`;b.onclick=()=>changeOutfit(o.id);outfits.appendChild(b)});wands.innerHTML='';home.ownedWands.map(id=>WANDS.find(o=>o.id===id)).filter(o=>o&&o.id!=='bare').forEach(o=>{let b=document.createElement('button');b.className=`closet-card ${home.wand===o.id?'active':''}`;b.innerHTML=`${wandHTML(o)}${o.name}`;b.onclick=()=>{home.wand=home.wand===o.id?'bare':o.id;saveHome();renderHome();setHomeMessage(home.wand==='bare'?'마법봉을 해제했어요.':`${o.name}을 장착했어요.`)};wands.appendChild(b)});transforms.innerHTML='';home.ownedTransforms.map(id=>TRANSFORMS.find(o=>o.id===id)).filter(o=>o&&o.id!=='none').forEach(o=>{let b=document.createElement('button');b.className=`closet-card ${home.transform===o.id?'active':''}`;b.innerHTML=`${transformHTML(o)}${o.name}`;b.onclick=()=>{home.transform=home.transform===o.id?'none':o.id;saveHome();renderHome();setHomeMessage(home.transform==='none'?'변신 아이템을 해제했어요.':`${o.name}을 착용했어요.`)};transforms.appendChild(b)});pets.innerHTML='';home.ownedPets.map(id=>PETS.find(o=>o.id===id)).filter(Boolean).forEach(o=>{let b=document.createElement('button');b.className=`closet-card ${home.pet===o.id?'active':''}`;b.innerHTML=o.id==='none'?o.name:`<img src="${o.file}" alt="">${o.name}`;b.onclick=()=>{home.pet=o.id;saveHome();renderHome();setHomeMessage(o.id==='none'?'펫과 함께하지 않아요.':`${o.name}와 함께해요.`)};pets.appendChild(b)})}
function clearStars(seconds){return seconds<=15*60?3:seconds<=20*60?2:1}
function grantReward(){let stage=state.stage||1,stars=clearStars(state.elapsed);if(developerMode)return{score:0,coins:0,shardGain:0,stars};home.stageStars=home.stageStars||{};home.stageStars[stage]=Math.max(home.stageStars[stage]||0,stars);home.unlockedStage=Math.max(home.unlockedStage||1,Math.min(MAX_STAGE,stage+1));let run=String(state.seed);if(home.rewarded.includes(run)){saveHome();return{score:0,coins:0,shardGain:0,stars}}let before=returnShards(),base={easy:500,medium:900,hard:1500}[state.level],score=Math.round(base*(state.mistakes===0?1.3:1)*(state.hints===(state.startHints??3)?1.2:1)),coins=Math.max(40,Math.floor(score/10));home.totalScore+=score;home.coins+=coins;home.rewarded.push(run);home.rewarded=home.rewarded.slice(-MAX_STAGE);let shardGain=returnShards()-before;saveHome();return{score,coins,shardGain,stars}}
function show(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));state.screen=id}
function stageLevel(stage){return stage<=30?'easy':stage<=70?'medium':'hard'}
function stageTier(stage){return stage<=30?'초급':stage<=70?'중급':'고급'}
function stageHints(stage){return stage<=20?3:stage<=50?2:stage<=80?1:0}
function isBossStage(stage){return BOSSES.some(b=>b.stage===stage)}
function renderStageMap(){home=loadHome();let box=$('#stageGrid');box.innerHTML='';for(let stage=1;stage<=MAX_STAGE;stage++){let unlocked=developerMode||stage<=home.unlockedStage,boss=isBossStage(stage),stars=boss?0:home.stageStars[stage]||0,bossDone=home.bossCleared.includes(stage),row=Math.floor((stage-1)/4),index=(stage-1)%4,reverse=row%2===1,b=document.createElement('button');b.className=`stage-node ${boss?'boss':''} ${reverse?'reverse':''} ${unlocked?'':'locked'} ${stars||bossDone?'completed':''} ${!developerMode&&stage===home.unlockedStage?'current':''}`;b.style.gridRow=row+1;b.style.gridColumn=reverse?4-index:index+1;b.disabled=!unlocked;b.setAttribute('aria-label',`${stage}탄 ${boss?'보스전 ':''}${unlocked?'선택 가능':'잠김'}${stars?`, 별 ${stars}개`:''}`);b.innerHTML=`${boss?'':`<span class="stage-stars" aria-label="별 ${stars}개 / 3개">${[1,2,3].map(n=>'<span class="stage-star '+(n<=stars?'filled':'empty')+'">★</span>').join('')}</span>`}${stage}<span class="stage-tier">${boss?'BOSS':''}</span>`;b.onclick=()=>boss?startBoss(stage):newPuzzle(stage);box.appendChild(b)}let focusStage=developerMode?1:home.unlockedStage,current=box.children[Math.min(MAX_STAGE-1,focusStage-1)];if(current)setTimeout(()=>{$('#stageMap').scrollTop=Math.max(0,current.offsetTop-180)},0)}
function startBoss(stage){home=loadHome();let boss=BOSSES.find(b=>b.stage===stage);if(!boss||(!developerMode&&stage>home.unlockedStage))return;let maxLunaHp=100+Math.floor(stage/10)*8,maxLunaMp=60;battleState={stage,boss,bossHp:boss.hp,lunaHp:maxLunaHp,maxLunaHp,lunaMp:maxLunaMp,maxLunaMp,usedTransform:false,usedPet:false,shield:0,weaken:0,over:false};stopClock();show('battle');renderBattle();$('#battleLog').textContent=`${boss.name} 등장!`}
function renderBattle(){if(!battleState)return;let s=battleState,b=s.boss,wand=WANDS.find(x=>x.id===home.wand)||WANDS[0],pet=PETS.find(x=>x.id===home.pet)||PETS[0],outfit=OUTFITS.find(x=>x.id===home.lastMagic)&&home.ownedOutfits.includes(home.lastMagic)?OUTFITS.find(x=>x.id===home.lastMagic):OUTFITS.find(x=>x.id==='magic');$('#battleTitle').textContent=`${s.stage}탄 · 보스전`;$('#bossName').textContent=b.name;$('#bossHpFill').style.width=`${Math.max(0,s.bossHp/b.hp*100)}%`;$('#bossHpText').textContent=`${Math.max(0,s.bossHp)} / ${b.hp}`;$('#lunaHpFill').style.width=`${Math.max(0,s.lunaHp/s.maxLunaHp*100)}%`;$('#lunaHpText').textContent=`${Math.max(0,s.lunaHp)} / ${s.maxLunaHp}`;$('#lunaMpFill').style.width=`${Math.max(0,s.lunaMp/s.maxLunaMp*100)}%`;$('#lunaMpText').textContent=`${Math.max(0,s.lunaMp)} / ${s.maxLunaMp}`;$('#bossSprite').style.setProperty('--bx',`${b.pos[0]*50}%`);$('#bossSprite').style.setProperty('--by',`${b.pos[1]*100}%`);$('#battleLuna').src=outfit.file;$('#battleWand').innerHTML=wand.id==='bare'?'':wandHTML(wand);$('#wandAttackInfo').textContent=`${wand.name} · MP 5`;$('#petSupportInfo').textContent=pet.id==='none'?'함께하는 펫 없음':`${pet.ability}${s.usedPet?' · 사용 완료':''}`;$('#hpPotionInfo').textContent=`보유 ${home.hpPotionStock}`;$('#mpPotionInfo').textContent=`보유 ${home.mpPotionStock}`;$('#wandAttack').disabled=s.over||s.lunaMp<5;$('#petSupport').disabled=s.over||s.usedPet||pet.id==='none';$('#useHpPotion').disabled=s.over||home.hpPotionStock<1||s.lunaHp>=s.maxLunaHp;$('#useMpPotion').disabled=s.over||home.mpPotionStock<1||s.lunaMp>=s.maxLunaMp;$('#battleRetry').hidden=!s.over||s.bossHp<=0}
function bossCounter(actionText){let s=battleState;if(s.bossHp<=0){winBoss(actionText);return}let raw=Math.max(0,s.boss.atk+Math.floor(Math.random()*5)-s.weaken),blocked=Math.min(raw,s.shield),damage=raw-blocked;s.shield=0;s.lunaHp=Math.max(0,s.lunaHp-damage);$('#battleLog').textContent=`${actionText} ${s.boss.name}의 반격! 루나가 ${damage} 피해를 입었어요.`;if(s.lunaHp<=0){s.over=true;$('#battleLog').textContent=`${actionText} 루나가 쓰러졌어요. 장비를 정비하고 다시 도전하세요.`}renderBattle()}
function wandAttack(){if(!battleState||battleState.over||battleState.lunaMp<5)return;let wand=WANDS.find(x=>x.id===home.wand)||WANDS[0],damage=Math.max(5,wand.atk+home.starlightLevel*3)+Math.floor(Math.random()*5);battleState.lunaMp-=5;battleState.bossHp=Math.max(0,battleState.bossHp-damage);bossCounter(`별빛 정화! ${damage} 피해.`)}
function useHpPotion(){let s=battleState;if(!s||s.over||home.hpPotionStock<1||s.lunaHp>=s.maxLunaHp)return;home.hpPotionStock--;let heal=Math.min(35,s.maxLunaHp-s.lunaHp);s.lunaHp+=heal;saveHome();bossCounter(`HP 포션 사용! 체력 ${heal} 회복.`)}
function useMpPotion(){let s=battleState;if(!s||s.over||home.mpPotionStock<1||s.lunaMp>=s.maxLunaMp)return;home.mpPotionStock--;let restore=Math.min(35,s.maxLunaMp-s.lunaMp);s.lunaMp+=restore;saveHome();bossCounter(`MP 포션 사용! 마력 ${restore} 회복.`)}
function transformAttack(){let s=battleState,tool=TRANSFORMS.find(x=>x.id===home.transform)||TRANSFORMS[0];if(!s||s.over||s.usedTransform||tool.id==='none'||s.lunaMp<20)return;s.lunaMp-=20;s.usedTransform=true;let damage=12+Math.floor(tool.price/55);s.bossHp=Math.max(0,s.bossHp-damage);bossCounter(`${tool.name} 발동! ${damage} 피해.`)}
function petSupport(){let s=battleState,pet=PETS.find(x=>x.id===home.pet)||PETS[0];if(!s||s.over||s.usedPet||pet.id==='none')return;s.usedPet=true;let text='';if(pet.id==='weasel'){s.bossHp=Math.max(0,s.bossHp-12);text='별빛 돌진! 12 피해.'}if(pet.id==='rabbit'){s.lunaHp=Math.min(s.maxLunaHp,s.lunaHp+35);text='달빛 응원! 체력 35 회복.'}if(pet.id==='fox'){s.shield=15;text='꼬리 보호막! 다음 피해를 15 막습니다.'}if(pet.id==='bat'){s.weaken=4;text='그림자 교란! 적 공격력이 4 감소합니다.'}if(pet.id==='owl'){s.bossHp=Math.max(0,s.bossHp-8);s.lunaHp=Math.min(s.maxLunaHp,s.lunaHp+18);text='별구름! 8 피해, 체력 18 회복.'}bossCounter(`${pet.name} 지원! ${text}`)}
function winBoss(actionText){let s=battleState,first=!home.bossCleared.includes(s.stage),reward=developerMode?0:first?s.boss.reward:0,score=developerMode?0:first?s.boss.reward*10:0;s.over=true;if(!developerMode){delete home.stageStars[s.stage];if(first){home.bossCleared.push(s.stage);home.coins+=reward;home.totalScore+=score}home.unlockedStage=Math.max(home.unlockedStage,Math.min(MAX_STAGE,s.stage+1));saveHome()}renderBattle();$('#battleLog').textContent=`${actionText} ${s.boss.name} 격파!`;$('#resultStats').innerHTML=`<b>${s.stage}탄 보스 클리어</b><br>${s.boss.name} 격파<br><br><b>+${score.toLocaleString('ko-KR')} RP · 포인트 +${reward}</b>${developerMode?'':s.stage<MAX_STAGE?`<br>${s.stage+1}탄이 열렸어요!`:'<br>100탄의 최종 보스를 쓰러뜨렸어요!'}`;$('#resultModal').classList.add('show')}
function newPuzzle(stage){stage=Math.min(MAX_STAGE,Math.max(1,+stage||1));let level=stageLevel(stage),seed=Math.imul(stage,2654435761)>>>0,p=transformed(LEVELS[level].p,seed),sol=solve(p),startHints=stageHints(stage);state={screen:'game',stage,level,puzzle:p,solution:sol,values:p.split('').map(Number),notes:Array.from({length:81},()=>[]),selected:-1,mistakes:0,hints:startHints,startHints,elapsed:0,paused:false,complete:false,noteMode:false,history:[],seed};$('#board').classList.remove('celebrate');show('game');render();startClock();save();syncResume();toast(`${stage}탄을 시작합니다 · 힌트 ${startHints}개`);}
function render(){const board=$('#board');board.innerHTML='';let selVal=state.selected>=0?state.values[state.selected]:0;for(let i=0;i<81;i++){let b=document.createElement('button'),r=Math.floor(i/9),c=i%9,v=state.values[i];b.className='cell';b.style.setProperty('--i',i);b.setAttribute('role','gridcell');b.setAttribute('aria-label',`${r+1}행 ${c+1}열, ${v||'빈칸'}${state.puzzle[i]!=='0'?', 고정된 수':''}${state.notes[i].length?', 후보 '+state.notes[i].join('·'):''}`);if(state.puzzle[i]!=='0')b.classList.add('given');if(v&&state.puzzle[i]==='0'&&String(v)!==state.solution[i])b.classList.add('conflict');if(i===state.selected)b.classList.add('selected');else if(state.selected>=0&&(r===Math.floor(state.selected/9)||c===state.selected%9||(Math.floor(r/3)===Math.floor(Math.floor(state.selected/9)/3)&&Math.floor(c/3)===Math.floor((state.selected%9)/3))))b.classList.add('related');if(selVal&&v===selVal)b.classList.add('same');if(v)b.textContent=v;else if(state.notes[i].length){let n=document.createElement('span');n.className='notes';for(let k=1;k<=9;k++){let s=document.createElement('i');s.textContent=state.notes[i].includes(k)?k:'';n.appendChild(s)}b.appendChild(n)}b.onclick=()=>select(i);board.appendChild(b)}
 $('#levelText').textContent=state.stage?`${state.stage}탄 · ${stageTier(state.stage)}`:LEVELS[state.level].ko;$('#timer').textContent=timeText(state.elapsed);$('#mistakes').textContent=state.mistakes;$('#hintCount').textContent=state.hints;$('#notes').classList.toggle('on',state.noteMode);$('#notes').innerHTML=`✎ 메모 ${state.noteMode?'ON':'OFF'}`;renderPad();}
function renderPad(){let pad=$('#numpad');pad.innerHTML='';for(let n=1;n<=9;n++){let b=document.createElement('button');b.className='num';b.textContent=n;b.setAttribute('aria-label',`${n} 입력`);if(state.values.filter(v=>v===n).length===9){b.classList.add('done');b.disabled=true}b.onclick=()=>input(n);pad.appendChild(b)}}
function select(i){if(!canEditPuzzle())return;if(state.paused||state.complete)return;state.selected=i;render();}
function snapshot(){state.history.push({values:[...state.values],notes:state.notes.map(x=>[...x]),mistakes:state.mistakes,hints:state.hints});if(state.history.length>100)state.history.shift()}
function input(n){if(!canEditPuzzle())return;let i=state.selected;if(state.complete)return;if(i<0){toast('먼저 빈칸을 선택하세요');return}if(state.puzzle[i]!=='0'){toast('처음부터 놓인 수는 바꿀 수 없습니다');return}if(state.noteMode&&state.values[i]){toast('확정 숫자를 지운 뒤 메모하세요');return}snapshot();if(state.noteMode){let a=state.notes[i],k=a.indexOf(n);k>=0?a.splice(k,1):a.push(n);a.sort();$('#message').textContent=`후보 ${n}${k>=0?' 제거':' 기록'}`;}else{state.notes[i]=[];state.values[i]=n;cleanNotes(i,n);let wrong=state.solution[i]!==String(n);if(wrong){state.mistakes++;$('#message').textContent='다시 살펴보세요 — 게임은 계속됩니다';}else{$('#message').textContent='좋은 수입니다';}}render();save();checkWin();}
function cleanNotes(i,n){let r=Math.floor(i/9),c=i%9;for(let j=0;j<81;j++){let rr=Math.floor(j/9),cc=j%9;if(rr===r||cc===c||(Math.floor(rr/3)===Math.floor(r/3)&&Math.floor(cc/3)===Math.floor(c/3)))state.notes[j]=state.notes[j].filter(x=>x!==n)}}
function erase(){if(!canEditPuzzle())return;let i=state.selected;if(state.complete||i<0||state.puzzle[i]!=='0')return;snapshot();state.values[i]=0;state.notes[i]=[];render();save()}
function undo(){if(!canEditPuzzle())return;if(state.complete)return;let h=state.history.pop();if(!h){toast('되돌릴 수가 없습니다');return}Object.assign(state,h);render();save()}
function hint(){if(!canEditPuzzle())return;let i=state.selected;if(state.complete)return;if(i<0||state.puzzle[i]!=='0'){toast('힌트를 받을 빈칸을 선택하세요');return}if(String(state.values[i])===state.solution[i]){toast('이미 올바른 수입니다');return}if(!state.hints){toast('힌트를 모두 사용했습니다');return}snapshot();state.values[i]=+state.solution[i];state.notes[i]=[];state.hints--;cleanNotes(i,state.values[i]);render();$$('.cell')[i]?.classList.add('hinted');save();checkWin()}
function checkWin(){if(!state.complete&&state.values.join('')===state.solution){state.complete=true;stopClock();save();$('#board').classList.add('celebrate');setTimeout(()=>{if(!state.complete)return;let reward=grantReward(),stage=state.stage||1,shard=reward.shardGain?'<br><b>✦ 귀환석 파편을 발견했어요!</b>':'';$('#resultStats').innerHTML=`<b>${stage}탄 완료 · ${'★'.repeat(reward.stars)}</b><br>${stageTier(stage)} · ${timeText(state.elapsed)}<br>실수 ${state.mistakes}회 · 힌트 ${(state.startHints??3)-state.hints}회<br><br><b>+${reward.score.toLocaleString('ko-KR')} RP · 포인트 +${reward.coins}</b>${stage<MAX_STAGE?`<br>${stage+1}탄이 열렸어요!`:'<br>100탄을 모두 완료했어요!'}${shard}`;$('#resultModal').classList.add('show');clearSave();},650)}}
function timeText(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function startClock(){stopClock();if(!canEditPuzzle())return;clock=setInterval(()=>{if(canEditPuzzle()){state.elapsed++;$('#timer').textContent=timeText(state.elapsed);if(state.elapsed%5===0)save()}},1000)}function stopClock(){clearInterval(clock);clock=null}
function pause(on=true){state.paused=on;$('#cover').classList.toggle('show',on);$('#pauseModal').classList.toggle('show',on);if(!on)startClock();else stopClock();save()}
function save(){try{localStorage.setItem(KEY,JSON.stringify({active:!state.complete,state}));}catch(e){}}
function clearSave(){try{localStorage.setItem(KEY,JSON.stringify({active:false}));syncResume();}catch(e){}}
function load(){try{let x=JSON.parse(localStorage.getItem(KEY)||'{}'),s=x?.state,valid=x?.active&&s&&!s.complete&&LEVELS[s.level]&&typeof s.puzzle==='string'&&s.puzzle.length===81&&typeof s.solution==='string'&&s.solution.length===81&&Array.isArray(s.values)&&s.values.length===81&&Array.isArray(s.notes)&&s.notes.length===81;return valid?x:null}catch(e){return null}}function syncResume(){}
function toast(t){let x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove('show'),1800)}
$('#myHome').onclick=openHome;$('#openShop').onclick=openShopScreen;$('#shopTitle').onclick=()=>show('title');$('#homeTitle').onclick=()=>show('title');$('#quickTransform').onclick=toggleTransform;$('#openCloset').onclick=()=>{closetOpen=!closetOpen;if(closetOpen)researchOpen=false;renderHome()};$('#openResearch').onclick=()=>{researchOpen=!researchOpen;if(researchOpen)closetOpen=false;renderHome()};$('#upgradeStarlight').onclick=upgradeStarlight;
$('#nova').onclick=()=>novaSay(['내가 현역이던 시절엔 마법봉도 직접 깎았지.','루미는 보기보다 눈치가 빠른 아이란다.','귀환석 파편은 다섯 조각을 모아야 한단다.','귀환석 파편에 관한 소문이라면… 더 강해진 뒤 다시 물어보렴.'][Math.floor(Math.random()*4)]);
$('#pet').onclick=()=>{let p=$('#pet'),pet=PETS.find(x=>x.id===home.pet),name=pet?.name.split(' ').pop()||'펫',lines=[`${name}가 쪼르르 달려왔어요!`,`${name}의 장식이 반짝였어요.`,`${name}가 반갑게 몸을 흔들었어요.`];p.classList.remove('happy');void p.offsetWidth;p.classList.add('happy');$('#homeMessage').textContent=lines[Math.floor(Math.random()*lines.length)]};
$('#newGame').onclick=()=>{show('difficulty');renderStageMap()};$('#toTitle').onclick=()=>show('title');$('#notes').onclick=()=>{if(!canEditPuzzle())return;state.noteMode=!state.noteMode;render();save()};$('#erase').onclick=erase;$('#undo').onclick=undo;$('#hint').onclick=hint;$('#pause').onclick=()=>pause(true);$('#continue').onclick=()=>pause(false);$('#restart').onclick=()=>{if(confirm('현재 진행을 지우고 처음부터 다시 시작할까요?'))newPuzzle(state.stage||1)};$('#quit').onclick=()=>{pause(false);show('title');stopClock()};$('#again').onclick=()=>{$('#resultModal').classList.remove('show');openHome()};$('#resultTitle').onclick=()=>{$('#resultModal').classList.remove('show');show('title')};
$('#developerMode').onclick=()=>{developerMode=true;show('difficulty');renderStageMap()};
$('#battleBack').onclick=()=>{show('difficulty');renderStageMap()};$('#wandAttack').onclick=wandAttack;$('#petSupport').onclick=petSupport;$('#useHpPotion').onclick=useHpPotion;$('#useMpPotion').onclick=useMpPotion;$('#battleRetry').onclick=()=>startBoss(battleState?.stage||20);
window.addEventListener('pagehide',()=>{saveHome();if(state.screen==='game'&&!state.complete)save()});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){saveHome();if(state.screen==='game'&&!state.complete)save()}});
document.addEventListener('keydown',e=>{if(state.screen!=='game'||$('#resultModal').classList.contains('show'))return;if(e.key==='Escape'){pause(!state.paused);return}if(state.paused||state.complete)return;if(/^[1-9]$/.test(e.key)){input(+e.key);return}if(['Backspace','Delete','0'].includes(e.key)){e.preventDefault();erase();return}if(e.key.toLowerCase()==='n'||e.code==='Space'){e.preventDefault();state.noteMode=!state.noteMode;render();save();return}if(e.key.toLowerCase()==='z'){e.preventDefault();undo();return}let d={ArrowLeft:-1,ArrowRight:1,ArrowUp:-9,ArrowDown:9}[e.key];if(d){e.preventDefault();if(state.selected<0){select(0);return}let i=state.selected+d;if(i>=0&&i<81&&(d===9||d===-9||Math.floor(i/9)===Math.floor(state.selected/9)))select(i)}});
syncResume();
})();
