(()=>{'use strict';
const KEY='gugungSudoku.v1';
const HOME_KEY='gugungHome.v1';
const LEVELS={easy:{ko:'고요',p:'530070000600195000098000060800060003400803001700020006060000280000419005000080079'},medium:{ko:'사유',p:'000260701680070090190004500820100040004602900050003028009300074040050036703018000'},hard:{ko:'심연',p:'005300000800000020070010500400005300010070006003200080060500009004000030000009700'}};
const ITEMS=[{id:'desk',name:'컴팩트 데스크',icon:'🖥️',price:0,pos:[0,0],scale:24},{id:'lamp',name:'무드 조명',icon:'💡',price:0,pos:[1,0],scale:18},{id:'cushion',name:'라운지 체어',icon:'🪑',price:0,pos:[2,0],scale:22},{id:'plant',name:'몬스테라 화분',icon:'🪴',price:0,pos:[3,0],scale:20},{id:'books',name:'매거진 세트',icon:'📚',price:100,pos:[0,1],scale:16},{id:'tea',name:'홈카페 세트',icon:'☕',price:130,pos:[1,1],scale:22},{id:'wardrobe',name:'모듈 옷장',icon:'🚪',price:180,pos:[2,1],scale:21},{id:'chest',name:'수납 바스켓',icon:'🧺',price:180,pos:[3,1],scale:17},{id:'clock',name:'미니멀 시계',icon:'⏰',price:260,pos:[0,2],scale:16},{id:'catbed',name:'포근한 소파',icon:'🛋️',price:330,pos:[1,2],scale:25},{id:'screen',name:'아트 포스터',icon:'🖼️',price:450,pos:[2,2],scale:19},{id:'moon',name:'네온 라이트',icon:'💜',price:600,pos:[3,2],scale:18},{id:'tree',name:'플로어 스탠드',icon:'🔆',price:800,pos:[0,3],scale:18}];
const OUTFITS=[{id:'casual',type:'daily',name:'데일리 후드',price:0,file:'assets/modern-woman.png'},{id:'dress',type:'daily',name:'코랄 원피스',price:220,file:'assets/modern-woman-dress.png'},{id:'school',type:'daily',name:'라벤더 교복',price:180,file:'assets/luna-school.png'},{id:'weekend',type:'daily',name:'포근한 주말룩',price:260,file:'assets/luna-weekend.png'},{id:'magic',type:'magic',name:'기본 변신폼',price:0,file:'assets/modern-woman-magic-lavender.png'},{id:'moonlight',type:'magic',name:'문라이트 드레스',price:700,file:'assets/modern-woman-moonlight-v2.png'},{id:'rose',type:'magic',name:'로즈 코멧 폼',price:900,file:'assets/luna-magic-rose.png'},{id:'midnight',type:'magic',name:'미드나이트 프리즘',price:1200,file:'assets/luna-magic-midnight.png'}];
const WANDS=[{id:'bare',name:'마법봉 없음',icon:'',price:0,atk:0,pos:[0,0]},{id:'branch',name:'낡은 나뭇가지',icon:'🌿',price:0,atk:3,pos:[0,0]},{id:'star',name:'별빛 마법봉',icon:'🪄',price:250,atk:12,pos:[1,0]},{id:'moon',name:'초승달 스태프',icon:'🌙',price:500,atk:24,pos:[0,1]},{id:'crystal',name:'크리스털 로드',icon:'💎',price:850,atk:40,pos:[1,1]}];
const PETS=[{id:'none',name:'함께하지 않기',file:'',price:0},{id:'weasel',name:'별족제비 루미',file:'assets/pet-lumi.png',price:0},{id:'rabbit',name:'별토끼 모모',file:'assets/pet-rabbit.png',price:320},{id:'fox',name:'별여우 코코',file:'assets/pet-star-fox-v2.png',price:430},{id:'bat',name:'달박쥐 네네',file:'assets/pet-moon-bat.png',price:520},{id:'owl',name:'구름부엉이 포포',file:'assets/pet-cloud-owl.png',price:610}];
const TRANSFORMS=[{id:'none',name:'변신 아이템 없음',price:0,pos:[0,0]},{id:'starPrism',name:'코멧 스타 키',price:300,pos:[0,0]},{id:'moonCompact',name:'미드나이트 아워',price:480,pos:[1,0]},{id:'flowerCompact',name:'문셸 콤팩트',price:650,pos:[0,1]},{id:'heartCompact',name:'아스트라 북 콤팩트',price:820,pos:[1,1]}];
const BOSSES=[{stage:10,name:'가시정원 슬라임',hp:50,atk:4,reward:120,pos:[0,0]},{stage:20,name:'초승달 까마귀',hp:85,atk:6,reward:220,pos:[1,0]},{stage:30,name:'태엽 갑옷게',hp:125,atk:8,reward:340,pos:[2,0]},{stage:40,name:'수정갈기 늑대',hp:170,atk:10,reward:480,pos:[0,1]},{stage:50,name:'별그림자 용',hp:230,atk:12,reward:700,pos:[1,1]}];
let state={screen:'title',level:'easy',puzzle:'',solution:'',values:Array(81).fill(0),notes:Array.from({length:81},()=>[]),selected:-1,mistakes:0,hints:3,elapsed:0,paused:false,history:[],seed:0};let clock=null;
let home=loadHome(),placing=null,placingRotation=0,decorateMode=false,closetOpen=false,lastSlot=-1,previewOutfit=null,previewKind='outfit',previewEquipment=null;
let battleState=null,developerMode=false;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function solve(str){const a=str.split('').map(Number);function go(){let idx=-1,best=null;for(let i=0;i<81;i++)if(!a[i]){const used=new Set();let r=Math.floor(i/9),c=i%9;for(let k=0;k<9;k++){used.add(a[r*9+k]);used.add(a[k*9+c]);}let br=Math.floor(r/3)*3,bc=Math.floor(c/3)*3;for(let y=0;y<3;y++)for(let x=0;x<3;x++)used.add(a[(br+y)*9+bc+x]);let opts=[];for(let n=1;n<=9;n++)if(!used.has(n))opts.push(n);if(!opts.length)return false;if(!best||opts.length<best.length){best=opts;idx=i;if(opts.length===1)break;}}if(idx<0)return true;for(const n of best){a[idx]=n;if(go())return true;a[idx]=0;}return false;}return go()?a.join(''):'';}
function mulberry32(a){return()=>{let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function transformed(base,seed){let rng=mulberry32(seed),shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a},map=shuffle([1,2,3,4,5,6,7,8,9]),bands=shuffle([0,1,2]),stacks=shuffle([0,1,2]),rows=bands.flatMap(b=>shuffle([0,1,2]).map(x=>b*3+x)),cols=stacks.flatMap(b=>shuffle([0,1,2]).map(x=>b*3+x)),out='';for(const r of rows)for(const c of cols){let d=+base[r*9+c];out+=d?map[d-1]:0}return out;}
function defaultHome(){return{roomVersion:2,coins:0,totalScore:0,unlockedStage:1,stageStars:{},bossCleared:[],owned:['desk','lamp','cushion','plant'],placed:[],ownedOutfits:['casual','magic'],outfit:'casual',lastDaily:'casual',lastMagic:'magic',ownedWands:['bare','branch'],wand:'branch',ownedTransforms:['none'],transform:'none',ownedPets:['none','weasel'],pet:'weasel',rewarded:[]}}
function loadHome(){try{let h=JSON.parse(localStorage.getItem(HOME_KEY)||'null');if(!(h&&Array.isArray(h.owned)&&Array.isArray(h.placed)))return defaultHome();if(h.roomVersion!==2){h.placed=[];h.roomVersion=2}let d=defaultHome(),m=Object.assign(d,h),valid=(list,catalog,required=[])=>[...new Set([...required,...(Array.isArray(list)?list:[])])].filter(id=>catalog.some(x=>x.id===id));m.rewarded=Array.isArray(m.rewarded)?m.rewarded.map(String).slice(-50):[];m.totalScore=Number.isFinite(+m.totalScore)?Math.max(0,+m.totalScore):0;m.coins=Number.isFinite(+m.coins)?Math.max(0,+m.coins):0;m.unlockedStage=Math.min(50,Math.max(1,Number.isInteger(+m.unlockedStage)?+m.unlockedStage:1));m.stageStars=m.stageStars&&typeof m.stageStars==='object'?Object.fromEntries(Object.entries(m.stageStars).filter(([k,v])=>+k>=1&&+k<=50&&[1,2,3].includes(+v)).map(([k,v])=>[k,+v])):{};m.bossCleared=Array.isArray(m.bossCleared)?[...new Set(m.bossCleared.map(Number).filter(n=>BOSSES.some(b=>b.stage===n)))]:[];m.owned=valid(m.owned,ITEMS,['desk','lamp','cushion','plant']);m.placed=m.placed.filter(p=>p&&m.owned.includes(p.id)&&Number.isInteger(p.slot)&&p.slot>=0&&p.slot<30).map(p=>({...p,rotation:[0,90,180,270].includes(p.rotation)?p.rotation:0}));m.ownedOutfits=valid(m.ownedOutfits,OUTFITS,['casual','magic']);m.outfit=m.ownedOutfits.includes(m.outfit)?m.outfit:'casual';m.lastDaily=m.ownedOutfits.includes(m.lastDaily)&&!isMagicOutfit(m.lastDaily)?m.lastDaily:'casual';m.lastMagic=m.ownedOutfits.includes(m.lastMagic)&&isMagicOutfit(m.lastMagic)?m.lastMagic:'magic';let legacyWands=Array.isArray(m.ownedWands)?m.ownedWands.map(id=>id==='none'?'branch':id):[];m.ownedWands=valid(legacyWands,WANDS,['bare','branch']);m.wand=m.wand==='none'?'branch':m.wand;m.wand=m.ownedWands.includes(m.wand)?m.wand:'branch';m.ownedTransforms=valid(m.ownedTransforms,TRANSFORMS,['none']);m.transform=m.ownedTransforms.includes(m.transform)?m.transform:'none';m.ownedPets=valid(m.ownedPets,PETS,['none','weasel']);m.pet=m.ownedPets.includes(m.pet)?m.pet:'weasel';return m}catch(e){return defaultHome()}}
function saveHome(){if(developerMode)return;try{localStorage.setItem(HOME_KEY,JSON.stringify(home))}catch(e){}}
function grantDeveloperInventory(){if(!developerMode)return;home.coins=10000;home.owned=ITEMS.map(x=>x.id);home.ownedOutfits=OUTFITS.map(x=>x.id);home.ownedWands=WANDS.map(x=>x.id);home.ownedTransforms=TRANSFORMS.map(x=>x.id);home.ownedPets=PETS.map(x=>x.id)}
function returnShards(h=home){return Math.min(5,Math.floor((h.rewarded?.length||0)/3))}
function spriteHTML(item,cls=''){let[x,y]=item.pos||[0,0];return `<span class="${cls} iso-sprite" style="--sx:${x*100/3}%;--sy:${y*100/3}%" role="img" aria-label="${item.name}"></span>`}
function wandHTML(item,cls=''){let[x,y]=item.pos||[0,0];return `<span class="${cls} wand-sprite" style="--wx:${x*100}%;--wy:${y*100}%" role="img" aria-label="${item.name}"></span>`}
function transformHTML(item,cls=''){let[x,y]=item.pos||[0,0];return `<span class="${cls} transform-sprite" style="--tx:${x*100}%;--ty:${y*100}%" role="img" aria-label="${item.name}"></span>`}
function setHomeMessage(t){let x=$('#homeMessage');if(x)x.textContent=t}
function renderGrowth(){let shards=returnShards();$("#homeShards").textContent=shards+" / 5 조각"}
function openHome(){show('home');stopClock();renderHome()}
function canPlace(item,slot,rotation=0){let row=Math.floor(slot/6),col=slot%6,centerX=16.7+col*13.3,centerY=43.8+row*9.6,size=item.scale||18,width=size,height=size*4/3,left=centerX-width/2,right=centerX+width/2,top=centerY-height*.68,bottom=centerY+height*.32;return left>=3&&right<=97&&top>=3&&bottom<=96}

function preserveInventoryScroll(draw){
 const ids=['home','gearCloset','ownedTools','catalog'];
 const positions=ids.map(id=>{const el=document.getElementById(id);return el?{el,x:el.scrollLeft,y:el.scrollTop}:null}).filter(Boolean);
 try{return draw()}finally{for(const p of positions){p.el.scrollLeft=p.x;p.el.scrollTop=p.y}}
}
function renderHome(){return preserveInventoryScroll(renderHomeContent)}
function renderCloset(){return preserveInventoryScroll(()=>{renderClosetContent();updateEmptyClosetRows()})}
function renderRoomInventory(){return preserveInventoryScroll(renderRoomInventoryContent)}
function renderCatalog(){return preserveInventoryScroll(renderCatalogContent)}
function updateEmptyClosetRows(){['ownedOutfits','ownedWands','ownedTransforms','ownedPets'].forEach(id=>{let row=document.getElementById(id);if(!row)return;let empty=row.childElementCount===0;row.hidden=empty;let label=row.previousElementSibling;if(label?.classList.contains('closet-label'))label.hidden=empty})}
function canEditPuzzle(){return state.screen==='game'&&!state.paused&&!state.complete}

function renderHomeContent(){
 home=loadHome();grantDeveloperInventory();if(isMagicOutfit(home.outfit))home.lastMagic=home.outfit;else home.lastDaily=home.outfit;$('#coins').textContent=home.coins.toLocaleString('ko-KR');
 let placed=$('#placed');placed.innerHTML='';home.placed.forEach(p=>{let item=ITEMS.find(x=>x.id===p.id);if(!item)return;let e=document.createElement('button'),row=Math.floor(p.slot/6),col=p.slot%6;e.className=`furniture ${placing===p.id?'placing-item':''}`;e.innerHTML=spriteHTML(item);e.title=decorateMode?`${item.name} 회수 또는 이동`:item.name;e.style.width=`${item.scale||18}%`;e.style.left=`${16.7+col*13.3}%`;e.style.top=`${43.8+row*9.6}%`;e.style.zIndex=6+row;e.style.transform=`translate(-50%,-68%) rotate(${p.rotation||0}deg)`;e.onclick=()=>{if(decorateMode){home.placed=home.placed.filter(x=>x!==p);placing=p.id;placingRotation=p.rotation||0;lastSlot=p.slot;saveHome();renderHome();setHomeMessage(`${item.name}을 회수했어요. 다른 칸을 누르면 다시 놓을 수 있어요.`)}};placed.appendChild(e)});
 let grid=$('#roomGrid');grid.innerHTML='';for(let i=0;i<30;i++){let s=document.createElement('button'),occupied=home.placed.some(p=>p.slot===i),item=ITEMS.find(x=>x.id===placing),blocked=!!(decorateMode&&item&&!canPlace(item,i,placingRotation));s.className=`slot ${occupied?'occupied':''} ${i===lastSlot?'chosen':''} ${blocked?'blocked':''}`;s.setAttribute('aria-label',`${i+1}번 배치 칸${occupied?', 사용 중':''}${blocked?', 테두리를 넘어 배치 불가':''}`);s.onclick=()=>placeAt(i);grid.appendChild(s)}
 $('#room').classList.toggle('decorate',decorateMode);$('#decorate').classList.toggle('primary',decorateMode);$('#decorate').textContent=decorateMode?'배치 완료':'방 꾸미기';$('#openCloset').classList.toggle('primary',closetOpen);$('#openCloset').textContent=closetOpen?'옷장 닫기':'옷장';
 let outfit=OUTFITS.find(x=>x.id===home.outfit)||OUTFITS[0],pet=PETS.find(x=>x.id===home.pet)||PETS[0],wand=WANDS.find(x=>x.id===home.wand)||WANDS[0],transform=TRANSFORMS.find(x=>x.id===home.transform)||TRANSFORMS[0];$('#cat').src=outfit.file;$('#cat').className='cat';$('#pet').hidden=pet.id==='none';if(pet.id!=='none'){$('#petImage').src=pet.file;$('#petName').textContent=pet.name.split(' ').pop()}$('#wandDisplay').innerHTML=wand.id==='bare'?'':wandHTML(wand);$('#transformDisplay').hidden=transform.id==='none';$('#transformDisplay').innerHTML=transform.id==='none'?'':transformHTML(transform);$('#quickTransform').textContent=isMagicOutfit(home.outfit)?'변신 해제':'✦ 변신하기';renderGrowth();renderRoomInventory();renderCloset();saveHome();renderShop()
}
function novaSay(text){let box=$('#novaTalk');if(box)box.innerHTML=`<strong>노바 아저씨</strong>${text}`}
function openShopScreen(){previewOutfit=home.outfit;previewKind='none';previewEquipment=null;show('shop');renderShop();novaSay(['어서 와. 오늘은 뭘 살 생각이니?','스도쿠 포인트는 현명하게 쓰는 게 좋아.','입어보는 건 무료란다. 천천히 골라봐.'][Math.floor(Math.random()*3)])}
function renderShop(){home=loadHome();if(developerMode)home.coins=10000;if(!OUTFITS.some(o=>o.id===previewOutfit))previewOutfit=home.outfit;let wallet=$('#shopCoins');if(wallet)wallet.textContent=home.coins.toLocaleString('ko-KR');if($('#dailyWardrobe'))renderWardrobe();if($('#fittingImage'))renderFitting();if(previewKind==='wand'){let w=WANDS.find(x=>x.id===previewEquipment);if(w)$('#fittingName').innerHTML=`${w.name}<small class="attack-stat">공격력 ${w.atk}</small>`}if($('#wandCatalog'))renderWands();if($('#transformCatalog'))renderTransforms();if($('#petCatalog'))renderPets();if($('#catalog'))renderCatalog()}
function isMagicOutfit(id){return OUTFITS.find(o=>o.id===id)?.type==='magic'}
function renderWardrobe(){$('#quickTransform').textContent=isMagicOutfit(home.outfit)?'변신 해제':'✦ 변신하기';renderOutfitGroup('#dailyWardrobe','daily','모든 일상 의상을 보유 중이에요.');renderOutfitGroup('#magicWardrobe','magic','모든 마법소녀 의상을 보유 중이에요.')}
function renderOutfitGroup(selector,type,emptyText){let box=$(selector),items=OUTFITS.filter(o=>o.type===type&&!home.ownedOutfits.includes(o.id));box.innerHTML='';if(!items.length){box.innerHTML=`<small class="sold-out">${emptyText}</small>`;return}items.forEach(o=>{let b=document.createElement('button');b.className=`outfit-btn locked ${previewKind==='outfit'&&previewOutfit===o.id?'active':''}`;b.innerHTML=`${type==='magic'?'✦ ':''}${o.name}<small>${o.price} P</small>`;b.onclick=()=>{previewKind='outfit';previewOutfit=o.id;previewEquipment=null;renderShop();novaSay(`${o.name}? 루나에게 잘 어울리는지 먼저 보렴.`)};box.appendChild(b)})}
function renderFitting(){let img=$('#fittingImage'),wand=$('#fittingWand'),transform=$('#fittingTransform'),pet=$('#fittingPet'),action=$('#fittingAction'),name=$('#fittingName'),status=$('#fittingStatus'),previewedOutfit=OUTFITS.find(x=>x.id===previewOutfit)||OUTFITS.find(x=>x.id===home.outfit)||OUTFITS[0];wand.hidden=true;transform.hidden=true;pet.hidden=true;action.hidden=false;img.src=previewedOutfit.file;name.parentElement.hidden=previewKind==='none';if(previewKind==='none'){name.textContent='';status.textContent='';action.hidden=true;action.onclick=null;return}if(previewKind==='wand'){let o=WANDS.find(x=>x.id===previewEquipment)||WANDS[0],owned=home.ownedWands.includes(o.id);wand.innerHTML=wandHTML(o);wand.hidden=false;name.textContent=o.name;status.textContent=owned?'보유 중':`루나 장착 미리보기 · 구매 ${o.price} P`;action.hidden=owned;action.textContent=`${o.price} P로 구매하기`;action.disabled=false;action.classList.add('buy');action.onclick=()=>buyEquip(o,'wand','ownedWands');return}if(previewKind==='transform'){let o=TRANSFORMS.find(x=>x.id===previewEquipment)||TRANSFORMS[0],owned=home.ownedTransforms.includes(o.id);transform.innerHTML=transformHTML(o);transform.hidden=false;name.textContent=o.name;status.textContent=owned?'보유 중':`루나 변신 아이템 미리보기 · 구매 ${o.price} P`;action.hidden=owned;action.textContent=`${o.price} P로 구매하기`;action.disabled=false;action.classList.add('buy');action.onclick=()=>buyEquip(o,'transform','ownedTransforms');return}if(previewKind==='pet'){let o=PETS.find(x=>x.id===previewEquipment)||PETS[1],owned=home.ownedPets.includes(o.id);pet.src=o.file;pet.alt=`미리 보는 ${o.name}`;pet.hidden=false;name.textContent=o.name;status.textContent=owned?'보유 중':`루나와 함께 보기 · 구매 ${o.price} P`;action.hidden=owned;action.textContent=`${o.price} P로 데려오기`;action.disabled=false;action.classList.add('buy');action.onclick=()=>buyEquip(o,'pet','ownedPets');return}let o=previewedOutfit,owned=home.ownedOutfits.includes(o.id);name.textContent=o.name;status.textContent=owned?'보유 중':`루나 착용 미리보기 · 구매 ${o.price} P`;action.hidden=owned;action.textContent=`${o.price} P로 구매하기`;action.disabled=false;action.classList.add('buy');action.onclick=()=>confirmPreviewOutfit(o)}
function confirmPreviewOutfit(o){if(home.ownedOutfits.includes(o.id))return;if(home.coins<o.price){toast(`포인트가 ${o.price-home.coins}점 부족합니다`);novaSay('입어보는 건 무료지만 구매할 포인트는 조금 부족하구나.');return}home.coins-=o.price;home.ownedOutfits.push(o.id);let next=OUTFITS.find(x=>!home.ownedOutfits.includes(x.id));previewOutfit=next?.id||home.outfit;previewKind='outfit';previewEquipment=null;saveHome();renderShop();toast(`${o.name} 구매 완료 · 내 방 옷장에 보관했어요`);novaSay('좋은 선택이야. 내 방 옷장에서 갈아입으렴.')}
function renderWands(){let current=WANDS.find(o=>o.id===home.wand)||WANDS[0],room=$('#wandDisplay');if(room)room.innerHTML=current.id==='bare'?'':wandHTML(current);let box=$('#wandCatalog'),items=WANDS.filter(o=>o.id!=='bare'&&!home.ownedWands.includes(o.id));box.innerHTML='';if(!items.length){box.innerHTML='<small class="sold-out">모든 마법봉을 보유 중이에요.</small>';return}items.forEach(o=>{let b=document.createElement('button');b.className=`shop-chip locked ${previewKind==='wand'&&previewEquipment===o.id?'active':''}`;b.innerHTML=`<strong>${wandHTML(o,'shop-wand')} ${o.name}<em class="attack-stat">공격력 ${o.atk}</em></strong><small>${o.price} P</small>`;b.onclick=()=>{previewKind='wand';previewEquipment=o.id;renderShop();novaSay(`${o.name}을 든 루나의 모습을 먼저 확인해 보렴.`)};box.appendChild(b)})}
function renderTransforms(){let box=$('#transformCatalog'),items=TRANSFORMS.filter(o=>o.id!=='none'&&!home.ownedTransforms.includes(o.id));box.innerHTML='';if(!items.length){box.innerHTML='<small class="sold-out">모든 변신 아이템을 보유 중이에요.</small>';return}items.forEach(o=>{let b=document.createElement('button');b.className=`shop-chip locked ${previewKind==='transform'&&previewEquipment===o.id?'active':''}`;b.innerHTML=`<strong>${transformHTML(o,'shop-transform')} ${o.name}</strong><small>${o.price} P</small>`;b.onclick=()=>{previewKind='transform';previewEquipment=o.id;renderShop();novaSay(`${o.name}을 착용한 모습을 확인해 보렴.`)};box.appendChild(b)})}
function renderPets(){let box=$('#petCatalog'),items=PETS.filter(o=>o.id!=='none'&&!home.ownedPets.includes(o.id));box.innerHTML='';if(!items.length){box.innerHTML='<small class="sold-out">모든 펫과 함께하고 있어요.</small>';return}items.forEach(o=>{let b=document.createElement('button');b.className=`shop-chip locked ${previewKind==='pet'&&previewEquipment===o.id?'active':''}`;b.innerHTML=`<strong>🐾 ${o.name}</strong><small>${o.price} P</small>`;b.onclick=()=>{previewKind='pet';previewEquipment=o.id;renderShop();novaSay(`${o.name}와 루나가 잘 어울리는지 먼저 보렴.`)};box.appendChild(b)})}
function buyEquip(o,field,list){if(home[list].includes(o.id))return;if(home.coins<o.price){toast(`포인트가 ${o.price-home.coins}점 부족합니다`);novaSay('포인트가 조금 부족하네. 퍼즐 의뢰를 하나 더 해결하고 와.');return}home.coins-=o.price;home[list].push(o.id);let catalog=field==='wand'?WANDS:field==='transform'?TRANSFORMS:PETS,next=catalog.find(x=>x.id!=='bare'&&x.id!=='none'&&!home[list].includes(x.id));if(next){previewEquipment=next.id}else{previewKind='outfit';previewEquipment=null;previewOutfit=home.outfit}saveHome();renderShop();toast(`${o.name} 구매 완료 · 내 방 옷장에 보관했어요`);novaSay(`${o.name}, 좋은 선택이야. 내 방에서 사용하렴.`)}
function changeOutfit(id){let o=OUTFITS.find(x=>x.id===id);if(!home.ownedOutfits.includes(id)){if(home.coins<o.price){toast(`포인트가 ${o.price-home.coins}점 부족합니다`);novaSay('그 옷은 아직 조금 비싸지? 실력을 보여주고 다시 오렴.');return}home.coins-=o.price;home.ownedOutfits.push(id);toast(`${o.name} 구매 완료`);novaSay('아주 잘 어울리겠구나. 탈의실은 바로 안쪽이야.')}home.outfit=id;saveHome();renderHome();if(isMagicOutfit(id)){$('#homeMessage').textContent=`${o.name}으로 변신!`;$('#room').classList.add('transforming');setTimeout(()=>$('#room').classList.remove('transforming'),800)}else $('#homeMessage').textContent=`${o.name}으로 갈아입었어요.`}
function toggleTransform(){changeOutfit(isMagicOutfit(home.outfit)?home.lastDaily:home.lastMagic)}
function renderClosetContent(){let panel=$('#gearCloset');panel.hidden=!closetOpen;if(!closetOpen)return;let outfits=$('#ownedOutfits'),wands=$('#ownedWands'),transforms=$('#ownedTransforms'),pets=$('#ownedPets');outfits.innerHTML='';home.ownedOutfits.map(id=>OUTFITS.find(o=>o.id===id)).filter(Boolean).forEach(o=>{let b=document.createElement('button');b.className=`closet-card ${home.outfit===o.id?'active':''}`;b.innerHTML=`<img src="${o.file}" alt="">${o.name}`;b.onclick=()=>changeOutfit(o.id);outfits.appendChild(b)});wands.innerHTML='';home.ownedWands.map(id=>WANDS.find(o=>o.id===id)).filter(o=>o&&o.id!=='bare').forEach(o=>{let b=document.createElement('button');b.className=`closet-card ${home.wand===o.id?'active':''}`;b.innerHTML=`${wandHTML(o)}${o.name}`;b.onclick=()=>{home.wand=home.wand===o.id?'bare':o.id;saveHome();renderHome();setHomeMessage(home.wand==='bare'?'마법봉을 해제했어요.':`${o.name}을 장착했어요.`)};wands.appendChild(b)});transforms.innerHTML='';home.ownedTransforms.map(id=>TRANSFORMS.find(o=>o.id===id)).filter(o=>o&&o.id!=='none').forEach(o=>{let b=document.createElement('button');b.className=`closet-card ${home.transform===o.id?'active':''}`;b.innerHTML=`${transformHTML(o)}${o.name}`;b.onclick=()=>{home.transform=home.transform===o.id?'none':o.id;saveHome();renderHome();setHomeMessage(home.transform==='none'?'변신 아이템을 해제했어요.':`${o.name}을 착용했어요.`)};transforms.appendChild(b)});pets.innerHTML='';home.ownedPets.map(id=>PETS.find(o=>o.id===id)).filter(Boolean).forEach(o=>{let b=document.createElement('button');b.className=`closet-card ${home.pet===o.id?'active':''}`;b.innerHTML=o.id==='none'?o.name:`<img src="${o.file}" alt="">${o.name}`;b.onclick=()=>{home.pet=o.id;saveHome();renderHome();setHomeMessage(o.id==='none'?'펫과 함께하지 않아요.':`${o.name}와 함께해요.`)};pets.appendChild(b)})}
function renderRoomInventoryContent(){let panel=$('#roomInventory'),box=$('#ownedTools');panel.hidden=!decorateMode;box.innerHTML='';if(!decorateMode)return;let owned=ITEMS.filter(item=>home.owned.includes(item.id));if(!owned.length){box.innerHTML='<p class="inventory-empty">가지고 있는 가구가 없어요.</p>';return}owned.forEach(item=>{let placement=home.placed.find(x=>x.id===item.id),placed=!!placement,card=document.createElement('div'),b=document.createElement('button');card.className='owned-card';b.className=`owned-tool ${placing===item.id?'active':''}`;b.innerHTML=`${spriteHTML(item,'tool-icon')}${item.name}<small>${placing===item.id?'선택됨':placed?'배치됨':'보유 중'}</small>`;b.onclick=()=>{placing=item.id;placingRotation=placement?.rotation||0;lastSlot=-1;renderHome();setHomeMessage(`${item.name}을 놓을 바닥 칸을 고르세요.`)};card.appendChild(b);if(placed){let rotate=document.createElement('button');rotate.className='rotate-item';rotate.textContent=`↻ 회전 ${placement.rotation||0}°`;rotate.onclick=()=>{let next=((placement.rotation||0)+90)%360;if(!canPlace(item,placement.slot,next)){toast('회전하면 방 테두리를 넘어가요');return}placement.rotation=next;saveHome();renderHome();setHomeMessage(`${item.name}을 ${next}도로 회전했어요.`)};card.appendChild(rotate);let take=document.createElement('button');take.className='retrieve';take.textContent='방에서 회수';take.onclick=()=>{home.placed=home.placed.filter(x=>x.id!==item.id);if(placing===item.id)placing=null;placingRotation=0;lastSlot=-1;saveHome();renderHome();setHomeMessage(`${item.name}을 보관함으로 회수했어요.`)};card.appendChild(take)}box.appendChild(card)})}
function renderCatalogContent(){let box=$('#catalog'),items=ITEMS.filter(item=>!home.owned.includes(item.id));box.innerHTML='';if(!items.length){box.innerHTML='<small class="sold-out">모든 가구를 보유 중이에요.</small>';return}items.forEach(item=>{let b=document.createElement('button');b.className='item';b.innerHTML=`${spriteHTML(item,'sprite')}${item.name}<small>포인트 ${item.price}</small>`;b.onclick=()=>{if(home.owned.includes(item.id)||b.disabled)return;b.disabled=true;if(home.coins<item.price){b.disabled=false;setHomeMessage(`포인트가 ${item.price-home.coins}점 부족해요.`);novaSay('포인트가 조금 부족하구나.');return}home.coins-=item.price;home.owned=[...new Set([...home.owned,item.id])];saveHome();setHomeMessage(`${item.name}을 샀어요! 내 방에서 배치할 수 있어요.`);novaSay(`${item.name}, 좋은 선택이야.`);renderShop()};box.appendChild(b)})}
function placeAt(slot){if(!decorateMode)return;if(!placing){toast('하단에서 가구를 먼저 선택하세요');return}if(home.placed.some(x=>x.slot===slot)){lastSlot=slot;renderHome();toast('주황색 칸은 이미 사용 중이에요');return}let item=ITEMS.find(x=>x.id===placing);if(!canPlace(item,slot,placingRotation)){lastSlot=slot;renderHome();toast('방 테두리를 넘어서 설치할 수 없어요');return}home.placed=home.placed.filter(x=>x.id!==placing);home.placed.push({id:placing,slot,rotation:placingRotation});lastSlot=slot;placing=null;placingRotation=0;saveHome();renderHome();$('#homeMessage').textContent=`${item.name}을 놓았어요. 민트색 칸이 선택한 자리예요.`}
function clearStars(seconds){return seconds<=15*60?3:seconds<=20*60?2:1}
function grantReward(){let stage=state.stage||1,stars=clearStars(state.elapsed);if(developerMode)return{score:0,coins:0,shardGain:0,stars};home.stageStars=home.stageStars||{};home.stageStars[stage]=Math.max(home.stageStars[stage]||0,stars);home.unlockedStage=Math.max(home.unlockedStage||1,Math.min(50,stage+1));let run=String(state.seed);if(home.rewarded.includes(run)){saveHome();return{score:0,coins:0,shardGain:0,stars}}let before=returnShards(),base={easy:500,medium:900,hard:1500}[state.level],score=Math.round(base*(state.mistakes===0?1.3:1)*(state.hints===(state.startHints??3)?1.2:1)),coins=Math.max(40,Math.floor(score/10));home.totalScore+=score;home.coins+=coins;home.rewarded.push(run);home.rewarded=home.rewarded.slice(-50);let shardGain=returnShards()-before;saveHome();return{score,coins,shardGain,stars}}
function show(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));state.screen=id}
function stageLevel(stage){return stage<=15?'easy':stage<=35?'medium':'hard'}
function stageTier(stage){return stage<=15?'초급':stage<=35?'중급':'고급'}
function stageHints(stage){return stage<=10?3:stage<=25?2:stage<=40?1:0}
function isBossStage(stage){return BOSSES.some(b=>b.stage===stage)}
function renderStageMap(){home=loadHome();let box=$('#stageGrid');box.innerHTML='';for(let stage=1;stage<=50;stage++){let unlocked=developerMode||stage<=home.unlockedStage,stars=home.stageStars[stage]||0,boss=isBossStage(stage),row=Math.floor((stage-1)/4),index=(stage-1)%4,reverse=row%2===1,b=document.createElement('button');b.className=`stage-node ${boss?'boss':''} ${reverse?'reverse':''} ${unlocked?'':'locked'} ${stars?'completed':''} ${!developerMode&&stage===home.unlockedStage?'current':''}`;b.style.gridRow=row+1;b.style.gridColumn=reverse?4-index:index+1;b.disabled=!unlocked;b.setAttribute('aria-label',`${stage}탄 ${boss?'번외 보스전 ':''}${unlocked?'선택 가능':'잠김'}${stars?`, 별 ${stars}개`:''}`);b.innerHTML=`<span class="stage-stars" aria-label="별 ${stars}개 / 3개">${[1,2,3].map(n=>'<span class="stage-star '+(n<=stars?'filled':'empty')+'">★</span>').join('')}</span>${stage}<span class="stage-tier">${boss?'BOSS':''}</span>`;b.onclick=()=>boss?startBoss(stage):newPuzzle(stage);box.appendChild(b)}let focusStage=developerMode?1:home.unlockedStage,current=box.children[Math.min(49,focusStage-1)];if(current)setTimeout(()=>{$('#stageMap').scrollTop=Math.max(0,current.offsetTop-180)},0)}
function startBoss(stage){home=loadHome();let boss=BOSSES.find(b=>b.stage===stage);if(!boss||(!developerMode&&stage>home.unlockedStage))return;let maxLunaHp=100+Math.floor(stage/10)*8;battleState={stage,boss,bossHp:boss.hp,lunaHp:maxLunaHp,maxLunaHp,usedTransform:false,usedPet:false,over:false};stopClock();show('battle');renderBattle();$('#battleLog').textContent=`${boss.name} 등장!`}
function renderBattle(){if(!battleState)return;let s=battleState,b=s.boss,wand=WANDS.find(x=>x.id===home.wand)||WANDS[0],transform=TRANSFORMS.find(x=>x.id===home.transform)||TRANSFORMS[0],pet=PETS.find(x=>x.id===home.pet)||PETS[0],outfit=OUTFITS.find(x=>x.id===home.lastMagic)&&home.ownedOutfits.includes(home.lastMagic)?OUTFITS.find(x=>x.id===home.lastMagic):OUTFITS.find(x=>x.id==='magic');$('#battleTitle').textContent=`${s.stage}탄 · 번외 보스전`;$('#bossName').textContent=b.name;$('#bossHpFill').style.width=`${Math.max(0,s.bossHp/b.hp*100)}%`;$('#bossHpText').textContent=`${Math.max(0,s.bossHp)} / ${b.hp}`;$('#lunaHpFill').style.width=`${Math.max(0,s.lunaHp/s.maxLunaHp*100)}%`;$('#lunaHpText').textContent=`${Math.max(0,s.lunaHp)} / ${s.maxLunaHp}`;$('#bossSprite').style.setProperty('--bx',`${b.pos[0]*50}%`);$('#bossSprite').style.setProperty('--by',`${b.pos[1]*100}%`);$('#battleLuna').src=outfit.file;$('#battleWand').innerHTML=wand.id==='bare'?'':wandHTML(wand);$('#wandAttackInfo').textContent=`${wand.name} · 공격력 ${wand.atk}`;$('#transformAttackInfo').textContent=transform.id==='none'?'장착한 아이템 없음':`${transform.name}${s.usedTransform?' · 사용 완료':''}`;$('#petSupportInfo').textContent=pet.id==='none'?'함께하는 펫 없음':`${pet.name}${s.usedPet?' · 지원 완료':''}`;$('#wandAttack').disabled=s.over;$('#transformAttack').disabled=s.over||s.usedTransform||transform.id==='none';$('#petSupport').disabled=s.over||s.usedPet||pet.id==='none';$('#battleRetry').hidden=!s.over||s.bossHp<=0}
function bossCounter(actionText){let s=battleState;if(s.bossHp<=0){winBoss(actionText);return}let damage=s.boss.atk+Math.floor(Math.random()*5);s.lunaHp=Math.max(0,s.lunaHp-damage);$('#battleLog').textContent=`${actionText} ${s.boss.name}의 반격! 루나가 ${damage} 피해를 입었어요.`;if(s.lunaHp<=0){s.over=true;$('#battleLog').textContent=`${actionText} 루나가 쓰러졌어요. 장비를 정비하고 다시 도전하세요.`}renderBattle()}
function wandAttack(){if(!battleState||battleState.over)return;let wand=WANDS.find(x=>x.id===home.wand)||WANDS[0],damage=Math.max(5,wand.atk)+Math.floor(Math.random()*5);battleState.bossHp=Math.max(0,battleState.bossHp-damage);bossCounter(`${wand.name} 공격! ${damage} 피해.`)}
function transformAttack(){let s=battleState,tool=TRANSFORMS.find(x=>x.id===home.transform)||TRANSFORMS[0];if(!s||s.over||s.usedTransform||tool.id==='none')return;s.usedTransform=true;let damage=12+Math.floor(tool.price/55);s.bossHp=Math.max(0,s.bossHp-damage);bossCounter(`${tool.name} 발동! ${damage} 피해.`)}
function petSupport(){let s=battleState,pet=PETS.find(x=>x.id===home.pet)||PETS[0];if(!s||s.over||s.usedPet||pet.id==='none')return;s.usedPet=true;let heal=20+Math.floor(pet.price/80),damage=4+Math.floor(pet.price/150);s.lunaHp=Math.min(s.maxLunaHp,s.lunaHp+heal);s.bossHp=Math.max(0,s.bossHp-damage);bossCounter(`${pet.name} 지원! 체력 ${heal} 회복, ${damage} 피해.`)}
function winBoss(actionText){let s=battleState,first=!home.bossCleared.includes(s.stage),reward=developerMode?0:first?s.boss.reward:0,score=developerMode?0:first?s.boss.reward*10:0;s.over=true;if(!developerMode){home.stageStars[s.stage]=3;if(first){home.bossCleared.push(s.stage);home.coins+=reward;home.totalScore+=score}home.unlockedStage=Math.max(home.unlockedStage,Math.min(50,s.stage+1));saveHome()}renderBattle();$('#battleLog').textContent=`${actionText} ${s.boss.name} 격파!`;$('#resultStats').innerHTML=`<b>${s.stage}탄 번외 보스 클리어 · ★★★</b><br>${s.boss.name} 격파<br><br><b>+${score.toLocaleString('ko-KR')} RP · 포인트 +${reward}</b>${developerMode?'':s.stage<50?`<br>${s.stage+1}탄이 열렸어요!`:'<br>50탄의 최종 보스를 쓰러뜨렸어요!'}`;$('#resultModal').classList.add('show')}
function newPuzzle(stage){stage=Math.min(50,Math.max(1,+stage||1));let level=stageLevel(stage),seed=Math.imul(stage,2654435761)>>>0,p=transformed(LEVELS[level].p,seed),sol=solve(p),startHints=stageHints(stage);state={screen:'game',stage,level,puzzle:p,solution:sol,values:p.split('').map(Number),notes:Array.from({length:81},()=>[]),selected:-1,mistakes:0,hints:startHints,startHints,elapsed:0,paused:false,complete:false,noteMode:false,history:[],seed};$('#board').classList.remove('celebrate');show('game');render();startClock();save();syncResume();toast(`${stage}탄을 시작합니다 · 힌트 ${startHints}개`);}
function render(){const board=$('#board');board.innerHTML='';let selVal=state.selected>=0?state.values[state.selected]:0;for(let i=0;i<81;i++){let b=document.createElement('button'),r=Math.floor(i/9),c=i%9,v=state.values[i];b.className='cell';b.style.setProperty('--i',i);b.setAttribute('role','gridcell');b.setAttribute('aria-label',`${r+1}행 ${c+1}열, ${v||'빈칸'}${state.puzzle[i]!=='0'?', 고정된 수':''}${state.notes[i].length?', 후보 '+state.notes[i].join('·'):''}`);if(state.puzzle[i]!=='0')b.classList.add('given');if(v&&state.puzzle[i]==='0'&&String(v)!==state.solution[i])b.classList.add('conflict');if(i===state.selected)b.classList.add('selected');else if(state.selected>=0&&(r===Math.floor(state.selected/9)||c===state.selected%9||(Math.floor(r/3)===Math.floor(Math.floor(state.selected/9)/3)&&Math.floor(c/3)===Math.floor((state.selected%9)/3))))b.classList.add('related');if(selVal&&v===selVal)b.classList.add('same');if(v)b.textContent=v;else if(state.notes[i].length){let n=document.createElement('span');n.className='notes';for(let k=1;k<=9;k++){let s=document.createElement('i');s.textContent=state.notes[i].includes(k)?k:'';n.appendChild(s)}b.appendChild(n)}b.onclick=()=>select(i);board.appendChild(b)}
 $('#levelText').textContent=state.stage?`${state.stage}탄 · ${stageTier(state.stage)}`:LEVELS[state.level].ko;$('#timer').textContent=timeText(state.elapsed);$('#mistakes').textContent=state.mistakes;$('#hintCount').textContent=state.hints;$('#notes').classList.toggle('on',state.noteMode);$('#notes').innerHTML=`✎ 메모 ${state.noteMode?'ON':'OFF'}`;renderPad();}
function renderPad(){let pad=$('#numpad');pad.innerHTML='';for(let n=1;n<=9;n++){let b=document.createElement('button');b.className='num';b.textContent=n;b.setAttribute('aria-label',`${n} 입력`);if(state.values.filter(v=>v===n).length===9){b.classList.add('done');b.disabled=true}b.onclick=()=>input(n);pad.appendChild(b)}}
function select(i){if(!canEditPuzzle())return;if(state.paused||state.complete)return;state.selected=i;render();}
function snapshot(){state.history.push({values:[...state.values],notes:state.notes.map(x=>[...x]),mistakes:state.mistakes,hints:state.hints});if(state.history.length>100)state.history.shift()}
function input(n){if(!canEditPuzzle())return;let i=state.selected;if(state.complete)return;if(i<0){toast('먼저 빈칸을 선택하세요');return}if(state.puzzle[i]!=='0'){toast('처음부터 놓인 수는 바꿀 수 없습니다');return}if(state.noteMode&&state.values[i]){toast('확정 숫자를 지운 뒤 메모하세요');return}snapshot();if(state.noteMode){let a=state.notes[i],k=a.indexOf(n);k>=0?a.splice(k,1):a.push(n);a.sort();$('#message').textContent=`후보 ${n}${k>=0?' 제거':' 기록'}`;}else{state.notes[i]=[];state.values[i]=n;cleanNotes(i,n);let wrong=state.solution[i]!==String(n);if(wrong){state.mistakes++;$('#message').textContent='다시 살펴보세요 — 게임은 계속됩니다';}else{$('#message').textContent='좋은 수입니다';}}render();save();checkWin();}
function cleanNotes(i,n){let r=Math.floor(i/9),c=i%9;for(let j=0;j<81;j++){let rr=Math.floor(j/9),cc=j%9;if(rr===r||cc===c||(Math.floor(rr/3)===Math.floor(r/3)&&Math.floor(cc/3)===Math.floor(c/3)))state.notes[j]=state.notes[j].filter(x=>x!==n)}}
function erase(){if(!canEditPuzzle())return;let i=state.selected;if(state.complete||i<0||state.puzzle[i]!=='0')return;snapshot();state.values[i]=0;state.notes[i]=[];render();save()}
function undo(){if(!canEditPuzzle())return;if(state.complete)return;let h=state.history.pop();if(!h){toast('되돌릴 수가 없습니다');return}Object.assign(state,h);render();save()}
function hint(){if(!canEditPuzzle())return;let i=state.selected;if(state.complete)return;if(i<0||state.puzzle[i]!=='0'){toast('힌트를 받을 빈칸을 선택하세요');return}if(String(state.values[i])===state.solution[i]){toast('이미 올바른 수입니다');return}if(!state.hints){toast('힌트를 모두 사용했습니다');return}snapshot();state.values[i]=+state.solution[i];state.notes[i]=[];state.hints--;cleanNotes(i,state.values[i]);render();$$('.cell')[i]?.classList.add('hinted');save();checkWin()}
function checkWin(){if(!state.complete&&state.values.join('')===state.solution){state.complete=true;stopClock();save();$('#board').classList.add('celebrate');setTimeout(()=>{if(!state.complete)return;let reward=grantReward(),stage=state.stage||1,shard=reward.shardGain?'<br><b>✦ 귀환석 파편을 발견했어요!</b>':'';$('#resultStats').innerHTML=`<b>${stage}탄 완료 · ${'★'.repeat(reward.stars)}</b><br>${stageTier(stage)} · ${timeText(state.elapsed)}<br>실수 ${state.mistakes}회 · 힌트 ${(state.startHints??3)-state.hints}회<br><br><b>+${reward.score.toLocaleString('ko-KR')} RP · 포인트 +${reward.coins}</b>${stage<50?`<br>${stage+1}탄이 열렸어요!`:'<br>50탄을 모두 완료했어요!'}${shard}`;$('#resultModal').classList.add('show');clearSave();},650)}}
function timeText(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function startClock(){stopClock();if(!canEditPuzzle())return;clock=setInterval(()=>{if(canEditPuzzle()){state.elapsed++;$('#timer').textContent=timeText(state.elapsed);if(state.elapsed%5===0)save()}},1000)}function stopClock(){clearInterval(clock);clock=null}
function pause(on=true){state.paused=on;$('#cover').classList.toggle('show',on);$('#pauseModal').classList.toggle('show',on);if(!on)startClock();else stopClock();save()}
function save(){try{localStorage.setItem(KEY,JSON.stringify({active:!state.complete,state}));}catch(e){}}
function clearSave(){try{localStorage.setItem(KEY,JSON.stringify({active:false}));syncResume();}catch(e){}}
function load(){try{let x=JSON.parse(localStorage.getItem(KEY)||'{}'),s=x?.state,valid=x?.active&&s&&!s.complete&&LEVELS[s.level]&&typeof s.puzzle==='string'&&s.puzzle.length===81&&typeof s.solution==='string'&&s.solution.length===81&&Array.isArray(s.values)&&s.values.length===81&&Array.isArray(s.notes)&&s.notes.length===81;return valid?x:null}catch(e){return null}}function syncResume(){}
function toast(t){let x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove('show'),1800)}
$('#myHome').onclick=openHome;$('#openShop').onclick=openShopScreen;$('#shopTitle').onclick=()=>show('title');$('#homeTitle').onclick=()=>show('title');$('#quickTransform').onclick=toggleTransform;$('#openCloset').onclick=()=>{closetOpen=!closetOpen;if(closetOpen)decorateMode=false;placing=null;lastSlot=-1;renderHome();setHomeMessage(closetOpen?'보유한 의상·마법봉·펫을 여기서 바꿀 수 있어요.':'옷장을 닫았어요.')};$('#decorate').onclick=()=>{decorateMode=!decorateMode;if(decorateMode)closetOpen=false;placing=null;lastSlot=-1;renderHome();$('#homeMessage').textContent=decorateMode?'하단에서 가구를 고르고 빈 바닥 칸을 누르세요. 주황색은 사용 중인 칸이에요.':'배치가 저장되었습니다.'};
$('#nova').onclick=()=>novaSay(['내가 현역이던 시절엔 마법봉도 직접 깎았지.','루미는 보기보다 눈치가 빠른 아이란다.','귀환석 파편은 다섯 조각을 모아야 한단다.','귀환석 파편에 관한 소문이라면… 더 강해진 뒤 다시 물어보렴.'][Math.floor(Math.random()*4)]);
$('#pet').onclick=()=>{let p=$('#pet'),pet=PETS.find(x=>x.id===home.pet),name=pet?.name.split(' ').pop()||'펫',lines=[`${name}가 쪼르르 달려왔어요!`,`${name}의 장식이 반짝였어요.`,`${name}가 반갑게 몸을 흔들었어요.`];p.classList.remove('happy');void p.offsetWidth;p.classList.add('happy');$('#homeMessage').textContent=lines[Math.floor(Math.random()*lines.length)]};
$('#newGame').onclick=()=>{show('difficulty');renderStageMap()};$('#toTitle').onclick=()=>show('title');$('#notes').onclick=()=>{if(!canEditPuzzle())return;state.noteMode=!state.noteMode;render();save()};$('#erase').onclick=erase;$('#undo').onclick=undo;$('#hint').onclick=hint;$('#pause').onclick=()=>pause(true);$('#continue').onclick=()=>pause(false);$('#restart').onclick=()=>{if(confirm('현재 진행을 지우고 처음부터 다시 시작할까요?'))newPuzzle(state.stage||1)};$('#quit').onclick=()=>{pause(false);show('title');stopClock()};$('#again').onclick=()=>{$('#resultModal').classList.remove('show');openHome()};$('#resultTitle').onclick=()=>{$('#resultModal').classList.remove('show');show('title')};
$('#developerMode').onclick=()=>{developerMode=true;show('difficulty');renderStageMap()};
$('#battleBack').onclick=()=>{show('difficulty');renderStageMap()};$('#wandAttack').onclick=wandAttack;$('#transformAttack').onclick=transformAttack;$('#petSupport').onclick=petSupport;$('#battleRetry').onclick=()=>startBoss(battleState?.stage||10);
window.addEventListener('pagehide',()=>{saveHome();if(state.screen==='game'&&!state.complete)save()});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){saveHome();if(state.screen==='game'&&!state.complete)save()}});
document.addEventListener('keydown',e=>{if(state.screen!=='game'||$('#resultModal').classList.contains('show'))return;if(e.key==='Escape'){pause(!state.paused);return}if(state.paused||state.complete)return;if(/^[1-9]$/.test(e.key)){input(+e.key);return}if(['Backspace','Delete','0'].includes(e.key)){e.preventDefault();erase();return}if(e.key.toLowerCase()==='n'||e.code==='Space'){e.preventDefault();state.noteMode=!state.noteMode;render();save();return}if(e.key.toLowerCase()==='z'){e.preventDefault();undo();return}let d={ArrowLeft:-1,ArrowRight:1,ArrowUp:-9,ArrowDown:9}[e.key];if(d){e.preventDefault();if(state.selected<0){select(0);return}let i=state.selected+d;if(i>=0&&i<81&&(d===9||d===-9||Math.floor(i/9)===Math.floor(state.selected/9)))select(i)}});
syncResume();
})();
